# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ostream < Formula
  desc "Command-line client for ostream.dev — stream a pipe over HTTP"
  homepage "https://ostream.dev"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ostream-dev/ostream-cli/releases/download/v0.2.0/ostream_0.2.0_darwin_amd64.tar.gz"
      sha256 "8eccf7336abeb91d997064b61a57c583f7ec73ad81d7ded725c5c6c956b83d19"

      define_method(:install) do
        bin.install "ostream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ostream-dev/ostream-cli/releases/download/v0.2.0/ostream_0.2.0_darwin_arm64.tar.gz"
      sha256 "92be8b398b0ca0f5c5e24a5b7065e73a4bb8171aa31480c102c6ae1d3ba32a53"

      define_method(:install) do
        bin.install "ostream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ostream-dev/ostream-cli/releases/download/v0.2.0/ostream_0.2.0_linux_amd64.tar.gz"
      sha256 "da6e459c87f1fd70e3ed5f2d691886d3b5eab991fe006efe665f03190982186f"
      define_method(:install) do
        bin.install "ostream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ostream-dev/ostream-cli/releases/download/v0.2.0/ostream_0.2.0_linux_arm64.tar.gz"
      sha256 "7b352870b239802b77c94aef4c2a08d6d8a9511ecbf2acd17bc8623915c6fa36"
      define_method(:install) do
        bin.install "ostream"
      end
    end
  end

  test do
    system "#{bin}/ostream --version"
  end
end
