# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ostream < Formula
  desc "Command-line client for ostream.dev — stream a pipe over HTTP"
  homepage "https://ostream.dev"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ostream-dev/ostream-cli/releases/download/v0.4.0/ostream_0.4.0_darwin_amd64.tar.gz"
      sha256 "60e8e37dfa0dae9390fea14e22560d39de42cb911809fddd4ca5972a4d022cf6"

      define_method(:install) do
        bin.install "ostream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ostream-dev/ostream-cli/releases/download/v0.4.0/ostream_0.4.0_darwin_arm64.tar.gz"
      sha256 "acb373df571e1a21e6d89ac3ffdfe21d3263adb5217312c4aa21dae90c0f92c4"

      define_method(:install) do
        bin.install "ostream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ostream-dev/ostream-cli/releases/download/v0.4.0/ostream_0.4.0_linux_amd64.tar.gz"
      sha256 "3131ad8620623fd3f9064cacbce018d7e4303c40e42f160ee4887abc1e31f19c"
      define_method(:install) do
        bin.install "ostream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ostream-dev/ostream-cli/releases/download/v0.4.0/ostream_0.4.0_linux_arm64.tar.gz"
      sha256 "bd5edd6bf533171a321dab55cd35b1c41b0148e11c92ae57b01e34db40aa7871"
      define_method(:install) do
        bin.install "ostream"
      end
    end
  end

  test do
    system "#{bin}/ostream --version"
  end
end
